# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Keith's Diary and Other Stuff"
email: your-email@domain.com
description: "Keith's Diary and Other Stuff"
author: "Keith Millar"

# Serving
port: 4000
host: 0.0.0.0
baseurl: "" # the subpath of your site, e.g. /blog
url: ""

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

#source:      .
destinationi_dir: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_source_dir: ./_data
collections: null

excerpt_separator: "{{ more }}"

highlighter: rouge

markdown_ext: markdown,mkd,mkdn,md

#gems: [jekyll-paginate]
